### ISSUE TITLE
401 on upload

### ISSUE THREAD

**Issue by remi-martin** [Piwigo/piwigo-flutter-app#105]
Http status error [401] on upload

**Comment by remi-martin** [comment]
While we are fixing the issue, here's the link for v1.0.0 https://play.google.com/apps/test/com.piwigo.piwigo_ng/101.

**Comment by revoltown** [comment]
> While we are fixing the issue, here's the link for v1.0.0 https://play.google.com/apps/test/com.piwigo.piwigo_ng/101.
link is not working.

**Comment by remi-martin** [comment]
Sorry, I can't find a working link to an older version. However, the 1.0.2 is available this repository's releases and soon on the Play store

**Comment by revoltown** [comment]
The app is working thank you, let's focus if you can on other issues I send to you... Please...Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: Remi Martin ***@***.***> Data: 28.03.2022  18:52  (GMT+01:00) Do: Piwigo/piwigo-flutter-app ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/piwigo-flutter-app] 401 on upload (Issue #105) 
Sorry, I can't find a working link to an older version. However, the 1.0.2 is available this repository's releases and soon on the Play store

**Comment by revoltown** [comment]
Hello, piwigo on iOS is not uploading photos too...Mateusz LamparskiWysłano z urządzenia mobilnego przy pomocy aplikacji Android Mail.
-------- Oryginalna wiadomość --------Od: Remi Martin ***@***.***> Data: 28.03.2022  18:52  (GMT+01:00) Do: Piwigo/piwigo-flutter-app ***@***.***> DW: revoltown ***@***.***>, Comment ***@***.***> Temat: Re: [Piwigo/piwigo-flutter-app] 401 on upload (Issue #105) 
Sorry, I can't find a working link to an older version. However, the 1.0.2 is available this repository's releases and soon on the Play store
