### ISSUE TITLE
Login issue on Huawei HUWEI MediaPad T3

### ISSUE THREAD

**Issue by remi-martin** [Piwigo/piwigo-flutter-app#137]
```
HandshakeException: Handshake error in client (OS Error: CERTIFICATE_VERIFY_FAILED: certificate has expired(Handshake.cc:393)) Huawei MediaTab T3 8.0 (KOB-W09), Android 7.0, EMUI 5.1.3 :(( But it works fine on my other devices. I got this error only on MediaTab T3.
```

**Comment by klaoun** [comment]
hello
[https://www.youtube.com/watch?v=kXlMjv0KOzg](url) ?

**Comment by remi-martin** [comment]
Oh, of course I didn't saw it at first but it's the SSL issue #74.

**Comment by remi-martin** [comment]
> hello [https://www.youtube.com/watch?v=kXlMjv0KOzg](url) ?

This is the fix I'm implementing, I just need to add some custom behaviors such as asking the users if they want to login with this certificate, and saving it if they accept to not ask it again.
