### ISSUE TITLE
Download from android: no icon displayed

### ISSUE THREAD

**Issue by Phil353556** [Piwigo/piwigo-flutter-app#138]
Hi,

It was working at least last year  (march 2022) with the new version NG.
However since a few months it doesn't work anymore: the icon that allows download is not displayed.
I tried several things like the plugin "custom download link"  but nothing appear on the mobile.
What I miss?
Thank you

**Comment by remi-martin** [comment]
Hi, The app does not support all plugins so adding "custom download link" to your piwigo won't fix the issue.

Download feature uses the same button as the share feature. If you still can't find it, please send me a screenshot where the icon have disappeared.

**Comment by Phil353556** [comment]
Hi, thank you for your answer and your help:
- Piwigo server :  v12.3 on a raspberry pi 
- Piwigo on mobile : Piwigo NG 1.2.1

-> "custom download link":  Ok I tried it, it is fine via a browser on a PC .. I didn't know / sorry 
-> screenshot done on a Samsung A22:
![image](https://user-images.githubusercontent.com/64729485/213766387-774ee581-410f-4127-b19b-9cb695dfafe6.png)

**Comment by remi-martin** [comment]
Alright, no problem. I assume that the download button is hidden when you are logged as a visitor and not as an admin nor webmaster.

**Comment by Phil353556** [comment]
Hi, Thanks for your answer
Good catch.
The screenshot 4 days ago, above, is done with the connection by a registered user. So the user must be logged to visualize photos/albums.

The screenshot done today, hereunder, with the same mobile but with the admin piwigo login and yes now all  the icons are there
I don't know if it is easy or not for you to fix. However thank you for your time and effort.

![image](https://user-images.githubusercontent.com/64729485/214371344-f227056d-546a-42f9-98c0-f881882ac2a3.png)

**Comment by Phil353556** [comment]
Bonjour @remi-martin ,  
Dois je comprendre que cela corrigé dans la version NG **2.0** actuellement en beta et non dans une version Piwigo NG 1.2.**2** par exemple ?
Merci pour votre retour

**Comment by remi-martin** [comment]
Bonjour,

Oui en effet, il n'y auras pas de 1.2.2.
Si tu as l'occasion de tester la bêta, pourras-tu me confirmer que le problème est bien corrigé ou non ?

**Comment by Phil353556** [comment]
Bonjour,
Ok.
Question juste pour être sûr de la démarche : 
- télécharger  app-release.apk 
- installer ce fichier sur le téléphone
- normalement la v2.0 est ok et peut être testée
- la v1.2.1 reste  toujours installé sur le téléphone en // 
  sinon faut que je trouve un téléphone sur lequel je peux "jouer" 
Est ce correct ?
Merci

**Comment by remi-martin** [comment]
Bonjour,

Les 2 versions (2.0.0-beta et 1.2.1) possèdent la même signature afin de pouvoir les utiliser sur le store. Du coup, lorsque tu vas installer la 2.0.0, elle va écraser la version précédente. Il me semble que le Play Store permet de revenir en arrière lorsqu'il s'agit d'une bêta, mais dans le cas contraire, il va falloir désinstaller la 2.0.0 pour reprendre la 1.2.1.

Est-ce que ça répond à ta question ?

Cdlt,
Rémi.
________________________________
De : Phil353556 ***@***.***>
Envoyé : lundi 6 février 2023 09:49
À : Piwigo/piwigo-flutter-app ***@***.***>
Cc : Rémi MARTIN ***@***.***>; Mention ***@***.***>
Objet : Re: [Piwigo/piwigo-flutter-app] Download from android: no icon displayed (Issue #138)


Bonjour,
Ok.
Question juste pour être sûr de la démarche :

  *   télécharger app-release.apk
  *   installer ce fichier sur le téléphone
  *   normalement la v2.0 est ok et peut être testée
  *   la v1.2.1 reste toujours installé sur le téléphone en //
sinon faut que je trouve un téléphone sur lequel je peux "jouer"
Est ce correct ?
Merci

**Comment by Phil353556** [comment]
Bonjour,
Essai sur un Galaxy S5 .... avec Android 6.0.1 .. oui c'est ancien
il a fallut biaiser pour pouvoir installer le apk, mais c'est Ok. la 2.0.0 de Piwigo NG est installée

1/ login avec un utilisateur lambda (ie pas admin) :  les boutons en bas sont disponibles, c'est top  merci !
2/ cf la copie d'écran y " No Photos   0 photos "   pourtant dans l'album y a bien 44 + 52 photos. 
Mais bon c'est une beta 
et typo  P p    Photos et  photos, 
3/ Je peux tester à loisir maintenant. Dites moi, si je peux aider,  c'est cool.
4/ Question facile (pour moi bien sûr)  : quelle serait la date de GA envisagée ?

Cordialement
Phil
![image](https://user-images.githubusercontent.com/64729485/216959744-2245f198-ae2e-44cf-b67e-6f04e97fbbef.png)

**Comment by remi-martin** [comment]
Super !
Concernant les textes de "Photos":
- "No Photos" veut dire que dans l'album actuel il n'y a pas de photos (sans compter les sous albums). Mais il est vrai que c'est pas pertinent donc je vais l'enlever.
- "0 photos" veut dire la même chose de "No Photos" donc c'est encore moins pertinent. Je suis d'accord, ça aurait plus d'intérêt si on affichait le nombre total (sous albums compris).

Je vais me réferer à l'application iOS pour savoir quoi mettre exactement au niveau de ces textes.

Ensuite, par "GA" je suppose que tu veut dire "Mise en production", dans ce cas je ne peux pas donner de date car ça dépend du nombre de bugs qui vont être rapportés, ainsi que le temps de la conception de l'auto-upload (qui est difficile à calculer car ça concerne un domaine que je ne maitrise pas encore).

Si jamais j'ai des fonctionnalités en particulier à faire tester, je n'hésiterais pas à t'en faire part.
Mais déjà merci pour ta contribution.

Cdlt,
Rémi.

**Comment by Phil353556** [comment]
ok
Comme mon téléphone perso est un apple ... iphone 7+ voici ce que cela donne pour la même vue :-) 
n'hésites pas à demander 
![image](https://user-images.githubusercontent.com/64729485/217034958-f678110d-db7f-45d8-ac6f-1c7011ea3e82.png)

Cordialement
Phil
