### ISSUE TITLE
Problem with adding multiple tags on uploading photos

### ISSUE THREAD

**Issue by kav72** [Piwigo/piwigo-flutter-app#139]
Hi! Trying to add multiple tags when uploading photos only adds one tag.
Piwigo NG Stable and Beta.
Piwigo Server v13.3.0
Plugins: Colored Tags, Tag groups

**Comment by remi-martin** [comment]
Hi, thanks for your feedback.

I'll investigate asap.

**Comment by remi-martin** [comment]
This will be fixed in 2.0.1, coming soon...

**Comment by kav72** [comment]
Hello, I tested and it works! Thank you!
