### ISSUE TITLE
Photo thumbs in cache?

### ISSUE THREAD

**Issue by roydenyates** [Piwigo/piwigo-flutter-app#143]
Latest v2.0 beta. Piwigo server is latest stable.

Cache is ca. 76MB. Opening app it seems album thumbs are cached. At least, they display immediately. However, entering a sub-album sees every picture thumb reload (closing circle animation), even when one simply leaves the album and then immediately re-enters it.

So, not a bug per see, unless this is not the desired outcome.  What is the expected behaviour?  Should thumbs be cached everywhere?

**Comment by remi-martin** [comment]
Hi,

The caching service is automatically handled by the framework (Flutter), so I guess you describe it's behavior.
But concerning the cache, it would be good to handle it more properly. Like you said re-entering an album without visiting others should not reload the thumbnails.
I'll see what I can do for that.

**Comment by remi-martin** [comment]
This is the plugin used for caching image thumbnails: [cached_network_image](https://pub.dev/packages/cached_network_image), based on [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager).

**Comment by remi-martin** [comment]
This should be fixed in 2.0.2 !

**Comment by roydenyates** [comment]
Brilliant. I will close when release available.

**Comment by roydenyates** [comment]
HUGE improvement! Thanks.
