### ISSUE TITLE
InfinityFree with Piwigo NG throws "Incorrect URL" error on login with

### ISSUE THREAD

**Issue by glkeswick** [Piwigo/piwigo-flutter-app#147]
I just installed the Piwigo NG 2.0.1 beta version on my Androd phone. On the log-in page I enter the URL for my self-hosted instance of Piwigo and my login credentials but when I click on Login I just get an error message "Incorrect URL" and the app will not launch. I have checked and re-entered the URL several times in case I made a typo.

Phone:
Android: 11
Piwigo NG: 2.0.1 beta

Server:
Piwigo 13.6.0 
Operating system: Linux
PHP: 7.4.8 
MySQL: 5.5.5-10.3.27-MariaDB 
SSL Cert issued by  ZeroSSL
Graphics Library: GD bundled (2.1.0 compatible)

**Comment by glkeswick** [comment]
Update: I just entered the URL and login credentials for my hosted Piwigo trial on piwigo.com and the app launched OK and I can see my albums.

So the problem seems to be in some way related to the URL of my self-hosted site. I don't really want to publish that URL in open forum but here's a masked version of what it looks like https://xxxxxxxxxxx.infinityfreeapp.com/photos/ in case that gives a clue as to why my URL is not accepted

**Comment by hardwareadictos** [comment]
same here on v2.0.2. Using NPM, was working here a week ago on the same version, no modifications made on the server side

**Comment by remi-martin** [comment]
Well, I still have no clue on this issue, I'll try to add more information for the login errors...

**Comment by remi-martin** [comment]
Yes, a lot ! But I'd like not to do it if it is unnecessary. Please can you tell me:

- Are you using a Self Signed Certificate (SSL) ?
- Do you use Apache Authentication / Http Authorization ?

If not, it might be an issue I have never encountered, and the access to your Piwigo might help a lot.

**Comment by glkeswick** [comment]
@remi-martin 

_Are you using a Self Signed Certificate (SSL) ?_

No - it's a free certificate from ZeroSSL obtained through my hosting service provider InfinityFree (app.infinityfree.net)

_Do you use Apache Authentication / Http Authorization ?_

I _think_ it's Apache but I'm afraid I know very little about authentication methods and software. Infinity Free hosting doesn't explicitly say anywhere that authentication is provided by Apache but poking around a little I find references to 'apache 2 handler' and I found an .htaccess file which I understand is something used for Apache authentication. Does any of that give you the information you need?

I'm happy to send you the URL for my PiWiGo site hosted on Infinity Free but I can't find a way in github to send a private message to you. Am I missing something or is there another way I can send you the URL privately?

**Comment by mathieuruellan** [comment]
Same issue with 13.7.0.
My ssl certificat is ok (lets encrypt).
It was working fine with v12.x

**Comment by remi-martin** [comment]
> Same issue with 13.7.0. My ssl certificat is ok (lets encrypt). It was working fine with v12.x

I don't have enought information to understand where the issue comes from... Is it still happening ?

**Comment by mathieuruellanmyscript** [comment]
@remi-martin yes it is still happening.
I can create a guest account on my server if you can't reproduce.

**Comment by remi-martin** [comment]
> @remi-martin yes it is still happening. I can create a guest account on my server if you can't reproduce.

I'd like to, it will help me a lot since it is not logged.

**Comment by mathieuruellanmyscript** [comment]
@remi-martin you can send me an email to mathieu.ruellan (at) gmail dot com i will response with url and login/password

**Comment by remi-martin** [comment]
InfinityFree seems to only accept Browser requests. This is why the app can't access the server.

see [InfinityFree Support](https://forum.infinityfree.net/t/this-site-requires-javascript-to-work-please-enable-javascript-in-your-browser-or-use-a-browser-with-javascript-support/18309).

**Comment by glkeswick** [comment]
Ah Ok. That never occurred to me. Thanks for pointing that out and really
sorry i wasted your time. Looks like i need to find me a new hosting site...

Andy

**Comment by remi-martin** [comment]
Maybe you can check with the Piwigo server team on the forum if there is a solution for this ...
[Forum EN](https://piwigo.org/forum/index.php)
[Forum FR](https://fr.piwigo.org/forum/index.php)

**Comment by glkeswick** [comment]
That's a good idea. In case i do end up having to move to a new hosting
service, can you advise me what is the specific feature/technology that
PiWiGo mobile app needs the host site to allow? I'm a technical novice and
this is all new to me.

Thanks

Andy
