### ISSUE TITLE
Error automatic uploading - 1 day

### ISSUE THREAD

**Issue by anderestebanez** [Piwigo/piwigo-flutter-app#161]
There is an issue when you try to config the automatic uploading in 1 per day. 
When you make the change the screen get blocked and you can't continue with it.
If you don't change this parameter there is no error.

**Comment by remi-martin** [comment]
I can confirm there is an error with this parameter. I'm looking for a fix

**Comment by remi-martin** [comment]
This should be fixed with 2.1.0, comming soon on Play Store.
