### ISSUE TITLE
Login form is not detected by password managers

### ISSUE THREAD

**Issue by mistic100** [Piwigo/piwigo-flutter-app#163]
I have BitWarden installed on my device. Normally the BitWarden button is displayed above the keyboard when a login form is detected in websites and apps. It does not on Piwigo NG login form.

I didn't test with other password managers.

Piwigo NG 2.1
BitWarden 2023.7.0
Android 11

**Comment by remi-martin** [comment]
It might be solved using AutoFillGroup : [https://github.com/flutter/flutter/issues/61301](https://github.com/flutter/flutter/issues/61301)

**Comment by remi-martin** [comment]
This solution works fine with BitWarden, Google and Samsung password managers.
