### ISSUE TITLE
app上传gif图，到服务器之后是静态的

### ISSUE THREAD

**Issue by renshinizhenhao** [Piwigo/piwigo-flutter-app#164]
app上传gif图，到服务器之后是静态的。我去浏览器网页上上传是正常的。

**Comment by remi-martin** [comment]
Hi, this issue comes from the compress method that was used to reduce image quality and remove metadatas according to their respective options in the app's settings. This method was only available for jpg, png and heic, not gif. 

I will stop using the Compress package and find another solution.

**Comment by remi-martin** [comment]
This is fixed and will be applied for next update 2.2.1.
