### ISSUE TITLE
Dialog Box for creating a new Album expands with text

### ISSUE THREAD

**Issue by shas0408** [Piwigo/piwigo-flutter-app#17]
When creating a new album, dialog box to capture album name and description grows along with the text added.

![Screen-rec](https://user-images.githubusercontent.com/7637947/122548945-96725080-d04f-11eb-89bb-fe1b8d1c11aa.gif)

A fix sized dialog-box and text-box would be better in terms of UX.

**Comment by remi-martin** [comment]
Hi, thanks for your feedback.
We'll try to fix the dialogs size depending on the device's size and orientation.

**Comment by remi-martin** [comment]
This will be fixed in the next update [see on play store](https://play.google.com/store/apps/details?id=com.piwigo.piwigo_ng) when it will be available.
