### ISSUE TITLE
Broken views

### ISSUE THREAD

**Issue by flowgunso** [Piwigo/piwigo-flutter-app#18]
On _0.0.6-alpha_, I have a few broken views: 
- The settings view is empty
- The category view show grey photos
- The image view is not navigable from the category view

I've debugged with a local build on the same device.

#### Settings view

The following exception is thrown from [lib/views/SettingsPage.dart#L135](https://github.com/Piwigo/piwigo-flutter-app/blob/6050abf78727c51691d553e32a8e752b8eb685db/lib/views/SettingsPage.dart#L135):
```
The following NoSuchMethodError was thrown building:
The method 'replaceAll' was called on null.
Receiver: null
Tried calling: replaceAll(",", ", ")
```

#### Category view
The following  exception is thrown from [lib/views/CategoryViewPage.dart#L303](https://github.com/Piwigo/piwigo-flutter-app/blob/6050abf78727c51691d553e32a8e752b8eb685db/lib/views/CategoryViewPage.dart#L303):
```
The following NoSuchMethodError was thrown building:
The method '[]' was called on null.
Receiver: null
Tried calling: []("url")
```

The _pwg.session.getStatus_ endpoint on my server does not return **upload_form_chunk_size** and  **upload_file_types**, which throws another exception `Unhandled Exception: Invalid argument(s) (value): Must not be null` at [lib/api/SessionAPI.dart#L80-L82](https://github.com/Piwigo/piwigo-flutter-app/blob/6050abf78727c51691d553e32a8e752b8eb685db/lib/api/SessionAPI.dart#L80-L82)

<details>
<summary>pwg.session.getStatus response</summary>

```xml
<rsp stat="ok">
<username>***********</username>
<status>normal</status>
<theme>clear</theme>
<language>en_GB</language>
<pwg_token>*********************************************</pwg_token>
<charset>utf-8</charset>
<current_datetime>2021-07-08 19:11:54</current_datetime>
<version>11.5.0</version>
<available_sizes>
<item>square</item>
<item>thumb</item>
<item>2small</item>
<item>xsmall</item>
<item>small</item>
<item>medium</item>
<item>large</item>
<item>xlarge</item>
<item>xxlarge</item>
</available_sizes>
</rsp>
```
</details>

<details>
<summary>Broken views screenshots</summary>

![album](https://user-images.githubusercontent.com/1887494/124986402-de2b3d00-e03b-11eb-817a-2babd133bf73.jpg)
![photos](https://user-images.githubusercontent.com/1887494/124986407-df5c6a00-e03b-11eb-93f5-6b0b762680ee.jpg)
![settings](https://user-images.githubusercontent.com/1887494/124986411-df5c6a00-e03b-11eb-99e6-c5afcd241bd5.jpg)
</details>

**Comment by remi-martin** [comment]
Hi, 0.0.7 is currently running on Google Play Store. Some issues have already been debugged, and i'll follow your workarounds for the others.

Thanks a lot for your feedback.

Best regards,
Rémi.
