### ISSUE TITLE
Version 2.3.0: Back arrow in image view no longer works.

### ISSUE THREAD

**Issue by abnerhale** [Piwigo/piwigo-flutter-app#193]
After today's update of Piwigo NG to version 2.3.0, you can no longer go back out of the view after opening an image. Neither the back arrow in the top left of the app nor the system's back button have any effect. Only opening another function, such as "Edit", allows you to exit the image view.

Xiaomi Android13
MIUI 14.0.7

**Comment by gueba** [comment]
I can confirm this behaviour on Lenovo Tablet/Android 7 and Allwinner TV-Box/Android 9

**Comment by remi-martin** [comment]
Hi, this is due to Flutter PopScope migration, will work on this ASAP
