### ISSUE TITLE
Real image fullscreen views

### ISSUE THREAD

**Issue by Nilvus** [Piwigo/piwigo-flutter-app#27]
First of all, this new piwigo app is on a good way and should quickly become better than official current one. 

Thus, it would be better with fullscreen modes for images (real ones) and especially for landscape images shown in landscape position of a smartphone. Title text and navigation buttons stay visible on top of the image (and even android 3 buttons bottom bar). On most app, a single tap in the center of the image make all things except image disappear. This would be good to have, in landscape and portrait modes.

**Comment by remi-martin** [comment]
Hi, thanks a lot for your feedback.

As an android user, I understand the request of this feature.
It will be added to our TODO list.

Thanks again,
Rémi.

**Comment by Nilvus** [comment]
I didn't precise it but I'm on android too. Thanks for your quick answer and good to read that you plan to implement that feature.

**Comment by remi-martin** [comment]
No need to precise you're on android because Piwigo NG is only for android and got named that way because of the former app.
That feature is quite logic in order to have a real full screen experience. I'll follow how basic phone's gallery app does it.
