### ISSUE TITLE
Wrong aspect ratio for videos in landscape orientation

### ISSUE THREAD

**Issue by zagl** [Piwigo/piwigo-flutter-app#29]
If the Smartphone is in portrait orientation the aspect ratio is correct.
In landscape orientation the video height is limited by the upper and lower app/action bars but is streched to the device width. Which results in a wrong aspect ratio.

**Comment by remi-martin** [comment]
Hi, thanks for your feedback.

We'll take a look on that issue.

**Comment by remi-martin** [comment]
This issue is fixed with 0.0.9
