### ISSUE TITLE
Crashes on Samsung Galaxy S7

### ISSUE THREAD

**Issue by ggtr1138** [Piwigo/piwigo-flutter-app#3]
Hi,

The app crashes directly on opening on my Samsung Galaxy S7 phone, model SM-G930F, even after rebooting the phone.

The error message is (in french) : "piwigo² s'est arrêté".

How can I send you a crash report from my phone?

**Comment by StefLedof** [comment]
Hello,
the application also crashes on an Samsung S6 with same message as @ggtr1138
Stéphane

**Comment by remi-martin** [comment]
Thanks for your feedback.

I'll also try the application on a Samsung Galaxy (S6 - 7) device.
I'll get back to you if i still can't find the problem.

**Comment by remi-martin** [comment]
Can I ask you guys on which version of android your devices are ? The application seems to work well for android 10 and 11.

**Comment by StefLedof** [comment]
Hello
Samsung S6 => Android 7.0

**Comment by remi-martin** [comment]
The application is not supported for devices under Android 9. We'll look for a solution in a future release

**Comment by ggtr1138** [comment]
Ok thanks Rémi. For my Samsung Galaxy S7, it's Android 8.0.0. I will try in a few weeks to install the "/e/" OS with Android 9 on this phone. I will post my feedback here.

**Comment by remi-martin** [comment]
I am trying to enable support for Android 6 and above and it seems promising ...

**Comment by remi-martin** [comment]
Piwigo NG should be fully available for Android 6 and above for the next alpha release coming this week

**Comment by ggtr1138** [comment]
This is great news, thank you! I'll wait patiently for the next alpha 👍

**Comment by StefLedof** [comment]
Good news, thank !
Stéphane
