### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by IzzySoft** [Piwigo/piwigo-flutter-app#37]
Currently, all your APKs identify as version 1.0.0 with versionCode 1 – which not only makes it hard to tell which version is installed, but also lets Android assume there is only a single version (Android uses `versionCode` to tell versions apart), making updates a bit more complicated.

May I suggest to adjust `versionName` ane `versionCode` properly – at least starting with the next version? That would then e.g. be 0.0.7 and 7. Thanks!

**Comment by remi-martin** [comment]
Hi, this has already be fixed along with the migration to the app store.

**Comment by remi-martin** [comment]
Currently working on 0.0.10+6 (6 is the version of code)

**Comment by IzzySoft** [comment]
> this has already be fixed along with the migration to the app store.

So your next tag/release should reflect it? If so, can you drop me a note here when it's available? I might add it to [my F-Droid repo](https://apt.izzysoft.de/fdroid) then. Unless you want to go straight for F-Droid itself that is.

**Comment by remi-martin** [comment]
It is already up from Piwigo 0.0.7+2 on the Google Play Store

**Comment by IzzySoft** [comment]
Google Play doesn't help with that. I'm looking at [your releases](https://github.com/Piwigo/piwigo-flutter-app/releases) – and there's no 0.0.7. Hint: not all Android users have Google accounts. For example, mine was closed by Google for "inactivity" years ago… Some of us on purpose run their devices without GApps :wink:
