### ISSUE TITLE
Accessing Piwigo over != 443 Port

### ISSUE THREAD

**Issue by TheBoneZone** [Piwigo/piwigo-flutter-app#39]
Its more a question than an Issue.

I have Piwigo running behind Traefik with a valid Lets Encrypt Certificate. If i type in the URL in a Browser:
https://mydomain:12000 everything works. 

But from the App, i get a invalid URL error. I assume that the App anticipated that Piwigo is running under the standard Port 443 and other Ports are ignored?

If i am right, any plans to add that Feature?

**Comment by remi-martin** [comment]
To request a piwigo server in the Flutter app, I use the [Dio plugin](https://pub.dev/packages/dio).

As you said, Dio must request on Port 443 but It might be possible to change the Port.

I'll give you a feedback on this issue when I'll have some news from the iOS devs.

**Comment by remi-martin** [comment]
I'm working on the Android app, but our goal is to copy the iOS app

**Comment by roydenyates** [comment]
Hi, my recent experience shows that the app will not accept say port 3443, but it will accept 65443. So go high ... But beware that the WAN port matches the forwarded LAN port, otherwise it will hiccup
 See this[](https://github.com/Piwigo/piwigo-flutter-app/issues/55#issuecomment-1008195769) .

**Comment by remi-martin** [comment]
Since this issue can be fixed locally, I'll close it.
