### ISSUE TITLE
First issues with Piwigo2

### ISSUE THREAD

**Issue by deljones** [Piwigo/piwigo-flutter-app#4]
Downloaded the apk today and successfully installed Piwigo2...

At last, an Android app to match or even beat the iOS version. A job well done to the team, a fantastic start. Looks great. The connection was quick and looking through the albums and photos was quite snappy. (550 photos for now)

Here are my observations on this version so far on a Galaxy A50, the latest Android.

- When creating a new album the create album dialogue box does not disappear, however, the new album does get created as I discovered when I kept pressing to confirm, I had about 15 new albums called "test". The dialog of course needs to disappear. You do get a message at the bottom confirming the creation of the album, however.
- Couldn't get the search function to work. Even typing in a known full file name didn't return anything.

That's it for me. I will keep testing until I break something! Waiting for more functionality. Bring it on.

Good job

Dj

**Comment by remi-martin** [comment]
Thanks for your feedback.

- Create album dialog is actually a bug and it will be fixed in a future release.
- Search feature is still under development, we just forgot to hide it from the users.

**Comment by remi-martin** [comment]
The changes have been pushed and will be available for the next alpha release coming this week, stay tuned.
