### ISSUE TITLE
Feature Request: background sync

### ISSUE THREAD

**Issue by ramack** [Piwigo/piwigo-flutter-app#52]
Together with (or after) #51 a new feature to hav background synchronization from one (or several) android local directories to dedicated alums into a remote gallery (if the configured network constraints are satisfied - like only on WLAN) would be great to have. This would be the second big benefit of using an app over the website.

**Comment by tanty** [comment]
I think this is a duplicated of #12 ?

**Comment by remi-martin** [comment]
dup of #100
