### ISSUE TITLE
Upload of pictures not working

### ISSUE THREAD

**Issue by waf06** [Piwigo/piwigo-flutter-app#54]
Hello, 
Photo uploading doesn't work on my phone. App is never uploading the photo(s) on my server. 
On standard Piwigo Android app, adding photo with community plugin works. 
I read on the forum that it might be an issue so I deactivated the plugin but still doesn't work. 
Is there something to set/check either on the server (Accessrights), the database (mysql version) or in Piwigo admin like in the synchronisation part? 

Anyway that's a promising App. 
Thanks a lot for putting this app to iOS level of functionality

**Comment by remi-martin** [comment]
Hi,
Thanks for your feedback, it is really appreciated.
Actually, there is no compatibility with the community plugin, but it will be done.

Concerning the upload, I can't give you an answer right now but I'll work on it.

**Comment by benbois** [comment]
Any progress here?

**Comment by remi-martin** [comment]
Hi,

Because of my studies, I'll not work on this project until 15 of November.

My apologies for the delay.
Regards,
Rémi Martin.

**Comment by benbois** [comment]
Merci Rémi.
Good to know.. Then we'll wait until 15 of November ;)

**Comment by EvgeniySpinov** [comment]
@remi-martin Please review PR: https://github.com/Piwigo/piwigo-flutter-app/pull/58 which fixes this

**Comment by remi-martin** [comment]
Hi, the upload has been fixed in 0.0.11.1. The release is available [here](https://github.com/Piwigo/piwigo-flutter-app/releases/tag/v0.0.11.1-beta) and will be available in a few days on the [Google Play Store](https://play.google.com/store/apps/details?id=com.piwigo.piwigo_ng)

**Comment by benbois** [comment]
@remi-martin 
Merci, thank you! 
The upload works as expected.

**Comment by remi-martin** [comment]
Good to hear :slightly_smiling_face:

**Comment by waf06** [comment]
A bit late maybe but I reinstalled the latest version and it works well now. We just need to wait a little bit to see the uploaded photos. I guess it is due to the resizing of the photo on the server.
Good job and thanks a lot !
