### ISSUE TITLE
Bug: Unable to enter gallery from Android 6.0 (invalid URL)

### ISSUE THREAD

**Issue by EvgeniySpinov** [Piwigo/piwigo-flutter-app#56]
Hi. 

First wanted to thank you for the great app, which actually compliments a great Piwigo. And it's much more functional than current Piwigo Android app. Please keep it moving!

I've tried to use app on my mobile (Android 6.01, MIUI Global 9.5.4.0) and I'm getting popup "Login Fail: Dio: invalid url", when trying to login. On the server side (according to access and error logs) - there is no request reaching the server, so it's not really clear what is wrong.

On other phone with Android 8.1.0, MIUI Global 10.3.1.0 - application works as intended. As well as it works on emulator (Bluestacks). Apparently something is wrong with my OS/Phone, but error message doesn't allow me to investigate.

Please advise.

**Comment by remi-martin** [comment]
Hi, sorry for the delay.

First, thanks for your feedback and your investment over this issue.

I'll check that later as I'll not work on this project for 2 weeks.

Regards,
Rémi Martin.

**Comment by remi-martin** [comment]
This issue seems to be fixed since we've merged #57
