### ISSUE TITLE
Unable to install on Android 8

### ISSUE THREAD

**Issue by remi-martin** [Piwigo/piwigo-flutter-app#59]
Check installation on lower Android versions

**Comment by EvgeniySpinov** [comment]
Android 6.0.1 version here - no issues with installation from Google Play.

**Comment by remi-martin** [comment]
A friend told me an error message from the Google play store when she tries to install the app from there. It says that her version is incompatible. 

The application is supposed to work between API 21 and 31.

I'll tell her to uninstall it in case it comes from the app's signature.

**Comment by remi-martin** [comment]
Hi, thanks for your feedback.

Please can you give me a screenshot so I can identify the problem ?
