### ISSUE TITLE
Camera upload does not update photo data from first run

### ISSUE THREAD

**Issue by yamanq** [Piwigo/piwigo-flutter-app#61]
After the first time uploading from camera, every subsequent "upload from camera" uses the same image as that first upload. This makes it impossible to upload photos from camera.

### Version:
I am using [piwigo_ng-0.0.11.1-beta](https://github.com/Piwigo/piwigo-flutter-app/releases/tag/v0.0.11.1-beta) with Android 10.

### How to reproduce:
1. Open an album
2. Use the FAB to "Take Photo"
3. Upload
4. Use FAB again to "Take Photo"
5. The image thumbnail and uploaded file will be the same as the image taken in step 2. This occurs regardless of restarting the app, using other buttons to upload photo, etc. Importantly, the title and description added in step 4 will still be uploaded correctly.

**Comment by yamanq** [comment]
After doing some investigation, I found that the issue occurs on Android 10 emulator, but not on an Android 11 emulator. After looking into the code, I believe the issue might be something to do with this [dependency](https://github.com/flutter-package/images_picker/blob/b1327e9bfb65c0195946d479518590026377cd11/android/src/main/java/com/chavesgu/images_picker/ImagesPickerPlugin.java#L241). I think it may be a good idea to switch from images_picker to image_picker, since the latter is developed by flutter.dev and much more popular. Also, I tried out a separate flutter app that uses image_picker and it doesn't have the same issue.

**Comment by remi-martin** [comment]
Hi, thanks for your feedback.

I'm planning to change the pickers plugins. To select files from the device, we'll use [file picker](https://pub.dev/packages/file_picker) and to take a picture / video, we'll use [image picker](https://pub.dev/packages/image_picker) as recommended.

**Comment by yamanq** [comment]
Is there a need for file_picker if image_picker already has a file picker?

**Comment by remi-martin** [comment]
image_picker doesn't allow to pick a image and a video at the same time
