### ISSUE TITLE
Document the use of .env

### ISSUE THREAD

**Issue by yamanq** [Piwigo/piwigo-flutter-app#64]
When setting up the project to begin contributing, I kept getting errors until I created a .env file with `PRIVACY_POLICIES="https://piwigo.org/mobile-apps-privacy-policy"`. I was unable to find other uses for the file, but this first value should be documented and possibly added to a .env on the repository.

**Comment by remi-martin** [comment]
Hi,

The .env file is not useful anymore as the app version is retrieved from the pubspec.yml.
I'll replace the PRIVACY_POLICIES variable to a hard coded static string.

In case we need a `.env` again, I'll add a `.env.tmp` file containing the required variables un-completed with documentation.
