### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by yamanq** [Piwigo/piwigo-flutter-app#69]
The app should allow searching on the main view and within each category, in the form of a search box at the top of view. The search results would then performed only on the currently visible albums/sub-albums. For example, opening the "2021" album and then searching would only search for images in the "2021" album and its sub-albums. The hint for the search box could be used to clarify this (e.g. "Search this album"). Images would be retrieved by the pwg.images.search endpoint and pagination could be added to the bottom of each scrolled view.

**Comment by remi-martin** [comment]
The iOS app does have a search bar, but only on the main view (root category) and it searches for all images in the Piwigo. We will discuss it's implementation for sub-categories.

But for now, I can only implement the search bar on root

**Comment by remi-martin** [comment]
Hi, here is the iOS search functionality:
![image](https://user-images.githubusercontent.com/71256855/153041806-586429d2-0995-423c-80f0-18e5dcabfcbc.png)
Which searches for all files of the Piwigo.

**Comment by yamanq** [comment]
Thank you for implementing this!
