### ISSUE TITLE
Feature request : play videos

### ISSUE THREAD

**Issue by skilleyes** [Piwigo/piwigo-flutter-app#7]
Would be great to be able to play videos. Only video poster is displayed at the moment.

**Comment by remi-martin** [comment]
Thanks for your feedback.

This is a known bug but it is not a priority at this time.
You can hope to see this feature in a future release (probably bêta or official release).

**Comment by pkrulz** [comment]
> 
> 
> Would be great to be able to play videos. Only video poster is displayed at the moment.

+1

**Comment by remi-martin** [comment]
mp4 Video Player is available in the latest version of Piwigo NG ([see on play store](https://play.google.com/store/apps/details?id=com.piwigo.piwigo_ng))

**Comment by ryanammoury** [comment]
Hi @remi-martin ,

I've tried playing videos, but so far only the thumbnail is displayed.
It may have to do with server-side configuration, it says on the app's Settings page : 

"This server handles these file types : jpg, jpeg, png, gif"

mp4 is missing.

Thanks in advance for your help.

**Comment by remi-martin** [comment]
Hi, in order to enable videos on your Piwigo, you need use the VideoJS plugin ;)

**Comment by skilleyes** [comment]
Yes, it is already enabled, it works well on the web interface.
