### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by yamanq** [Piwigo/piwigo-flutter-app#71]
It looks like this project does not have a license attached right now. What is the license that this code is released under? I suggest GPLv2 as this is the license of the main Piwigo repository.

**Comment by yamanq** [comment]
@remi-martin Thank you for adding the license. I think this can be closed unless there are other changes you would like to make.

**Comment by remi-martin** [comment]
I'll add an in-app page for the License. But for now, the Github file is enough.
