### ISSUE TITLE
Please support the piwigo_privacy plugin

### ISSUE THREAD

**Issue by Catfriend1** [Piwigo/piwigo-flutter-app#76]
Version: recent github release
Piwigo 2.10 server with yonyah's privacy plugin.

Result: I can login but pictures do not show up, just white boxes per picture.

Thank you.

**Comment by remi-martin** [comment]
Hi, thanks for your feedback.

I'll take a look at this issue.

**Comment by Catfriend1** [comment]
I'm no longer using the plugin ...

**Comment by remi-martin** [comment]
Okay, I'll still look to add compatibility for plugins in the app later.

**Comment by ghost** [comment]
please delete issue
