### ISSUE TITLE
Instructions on how to build this app

### ISSUE THREAD

**Issue by Catfriend1** [Piwigo/piwigo-flutter-app#77]
Hi,

I'd like to build this app myself to see where problems come from. How can I do it? I've already built "standard" Android apps with Android Studio and now downloaded the flutter-sdk surplus. My PATH is extended to have flutter-sdk/bin in it. 

Which commands do I need to run from here to build piwigo-flutter-app?

Thank you.

Kind regards
Catfriend1

Step 1:
- Download flutter sdk from: https://docs.flutter.dev/get-started/install/windows
- Extract ZIP to: C:\GitHub\piwigo-flutter-app-prereq\flutter-sdk
- Turn off telemetry

flutter-env.cmd
```
@echo off
REM
SET PATH=%PATH%;%~dps0\flutter-sdk\bin
REM
call flutter config --no-analytics
REM
cmd
REM
goto :eof
```

- Clone this git to: C:\GitHub\piwigo-flutter-app
- Edit file: "C\GitHub\piwigo-flutter-app\android\local.properties"

```
sdk.dir=C\:\\Sdk\\Android\\Sdk
flutter.sdk=C\:\\GitHub\\piwigo-flutter-app-prereq\\flutter-sdk
```

- Command line: Run "flutter-env.cmd"

```
cd /d "C:\GitHub\piwigo-flutter-app"
flutter clean
flutter pub get
```

- Whitelist hosts to allow bypassing SSL inspection

```
^https://www\.schemastore\.org/
^https://repo\.maven\.apache\.org/
```

---

Error - if flutter sdk cannot be found - Solution: see above.
```
A problem occurred evaluating settings 'android'.
> flutter.sdk not set in local.properties. Expression: (flutterSdkPath != null). Values: flutterSdkPath = null
```

**Comment by Catfriend1** [comment]
Error 2:

```
C:\GitHub\piwigo-flutter-app\.dart_tool\package_config.json does not exist.
Did you run this command from the same directory as your pubspec.yaml file?
```

**Comment by Catfriend1** [comment]
Error 3: 

```
> Task :app:validateSigningDebug UP-TO-DATE

FAILURE: Build failed with an exception.

* Where:
Script 'C:\GitHub\piwigo-flutter-app-prereq\flutter-sdk\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'F:\GitHub\piwigo-flutter-app-prereq\flutter-sdk\bin\flutter.bat'' finished with non-zero exit value 1

```

**Comment by Catfriend1** [comment]
Output dir for APK: C:\GitHub\piwigo-flutter-app\build\app\outputs\flutter-apk

**Comment by ghost** [comment]
please delete issue
