### ISSUE TITLE
Thumbnails not appearing inside album/sub album

### ISSUE THREAD

**Issue by smittyely** [Piwigo/piwigo-flutter-app#8]
Just installed NG looks good.  However I only see thumbnails for the album and not for images inside the album.

I have tried with albums with a low image count and with high image counts and seem to get the same result.

The is no indication that the app is performing a background task so I presume it has stalled?

I have tried to restart with no better result.

**Comment by remi-martin** [comment]
Thanks for your feedback.

What type of file are you trying to show (.png, .jpg, .mp4, ...) and how many images are inside the album ? That could help me to find out what the problem is.

**Comment by remi-martin** [comment]
Hi @smittyely , can you give me your Piwigo's address so I can try to reproduce this bug ? By the way, what android version are you using ?

**Comment by smittyely** [comment]
Hi @remi-martin ,

Here is the link for the repository, still a work in progress.  http://andrewsmith.ca/photos/ 

I use a OnePlus device, so the OS is Oxygen OS 11.0.0.2.GM21AA

**Comment by remi-martin** [comment]
Bad news: I can't reproduce this bug. I can see all your photos.
I think the problem comes from the unsecured certificate as you are using HTTP and not HTTPS.

**Comment by smittyely** [comment]
Hi @remi-martin 

I have checked in to the SSL there was an issue which is now resolved I think and they are still not appearing.

I will try a reinstall and see.

**Comment by remi-martin** [comment]
Hello @smittyely. Because I can't reproduce this bug, can you try the following if you haven't tryiedit yet:
- Log into your piwigo as a guest.
- See if this bug still happens in another server (you cant try https://demo1.piwigo.com).

Thanks by advance for your cooperation

**Comment by smittyely** [comment]
I am not able to change the credentials as the app logs me in automatically, and I cannot see a LOG OUT.

I have tried to quickly delete the details on start up, and also a reinstall, which automatically adds the credentials that existed before the uninstall.

**Comment by remi-martin** [comment]
You can log out through the settings

**Comment by smittyely** [comment]
> You can log out through the settings

I do not see any options in settings.
![Screenshot_20210516-084956](https://user-images.githubusercontent.com/75308411/118389847-d9da3900-b623-11eb-9838-16b89efc0432.jpg)

**Comment by remi-martin** [comment]
You are supposed to see something like this ![Screenshot_20210516-095230.jpg](https://user-images.githubusercontent.com/71256855/118389926-abad2700-b62c-11eb-9fa5-5263d97d5685.jpg)

I'll try to fix this for the next alpha release...

**Comment by smittyely** [comment]
@remi-martin I installed version .4 and can log in as a guest and as a user, I can see the thumbnails.  But still do not see the Settings.

I will keep my eyes open for the next build.
