### ISSUE TITLE
Group permissions doesn't work

### ISSUE THREAD

**Issue by ste69008** [Piwigo/piwigo-flutter-app#84]
I have users included in groups.
All my permissions are affected to groups
When i log in (all versions, included 0.13), my album list is empty.

- Users rights are ok in desktop mode with chrome, firefox....
- admin account works well on android app

Piwigo 12.2 on docker

**Comment by remi-martin** [comment]
Hi, thanks for your feedback.

I'll check that right away.

**Comment by ste69008** [comment]
Hi,
Unchanged in 1.0.3

**Comment by robinofe** [comment]
I can confirm in current version 1.0.3 the problem still persists,
would be great if this could be fixed

**Comment by remi-martin** [comment]
Hi, is the issue still up in 1.1.X ? I'm trying to reproduce it again but I can't see the problem

**Comment by ste69008** [comment]
Hi, yes problem stil exist in 1.1.1.
How can i help you ? do you need logs ?

**Comment by ste69008** [comment]
I tested it  again and i foud the problem : it's "community" plugin !
If i disable it, it works.
Sorry for the inconvenience

**Comment by remi-martin** [comment]
That's weird, but thanks for your workarounds. 
By the way, do you use a self hosted piwigo or Piwigo.com ?

**Comment by ste69008** [comment]
I use a self hosted piwigo in docker container for my familly
I like your tool, thank you for the time spent

**Comment by remi-martin** [comment]
No problem, glad you enjoy it. We will try to make it better over time

**Comment by remi-martin** [comment]
Hi, I have updates !
The route pwg.categories.getList returns only the albums the community user can upload to, and not the albums he can see. iOS app is using a weird solution to solve this, but I'll try to apply it to Piwigo NG.

- Use `pwg.categories.getList` with `faked_by_community = false` when Community is installed. 
- Use `pwg.community.categoriesGetList` to get the albums where the user can upload.

**Comment by remi-martin** [comment]
Piwigo NG 1.2.0 is out on Github and may close this issue
