### ISSUE TITLE
Images dont upload as community user with permissions

### ISSUE THREAD

**Issue by pkrulz** [Piwigo/piwigo-flutter-app#9]
I am not able to upload photos as a community user in an album although I can upload via the web interface.

When I upload, it takes me to a screen which says 1 photo and a big orange bar says upload.
When I click upload a grey ribbon at bottom has a rotating symbol on right. It stops after a while. No photos are uploaded.

This however works when I try to do this as an admin. Basically the community plugin functionality is not reflected since I do have rights to upload as a community user and can upload via the web interface.

Trying to move a photo did not work either as a community user. A blank screen showed up from bottom which had a rotating wheel. The rotation never stopped.

Platform
Samsung Galaxy M21
Android version 11
Kernel: 4.14.113-21183318

**Comment by remi-martin** [comment]
Thanks for your feedback.
The application is not handling request errors to the Piwigo API yet, this is why there is no message to say if it worked or not. They will be added in a future release.

I haven't try the application as a community user yet. I'll try later.

**Comment by remi-martin** [comment]
This issue doesn't comes from the android app but from the server with the update 11. This issue seems to only affect the async upload. I'll add an option to the settings page to switch between normal upload and upload async in a future release.

**Comment by pkrulz** [comment]
Is there anything that can be done on the server side.

I did not exactly under how the system works when done as an admin

**Comment by croulibri** [comment]
Hello,

Thanks for this promising app :-)
I am using Piwigo in a personal install with Community plugin activated as we use it for family photo sharing.

With Piwigo NG, as a community user, I can:
 - see photos in folders where I am authorised to upload pictures ("my folders")

but  I can't:
 - upload photos in folders where I am authorised (it works through web interface)
 - see photos in other users folders (where I can only see and not upload pictures, but it works through web interface)

**Comment by plegall** [comment]
As the developer of the Community plugin, I have to work on this problem. The iOS app is also affected by this problem. I don't understand the problem yet... but I will!

**Comment by pkrulz** [comment]
Dear @plegall 
Were you able to identify the source of this issue.

An additional android app as I understand is able to upload images even for community users. It exposes more of piwigo functionality by this extension
https://piwigo.org/ext/extension_view.php?eid=880

Would this additionally exposed functionality help in fixing the issue

**Comment by remi-martin** [comment]
Upload for community users with Piwigo NG does not work with Piwigo 11 and lower versions.

**Comment by pkrulz** [comment]
I have Piwigo Server 12
But I am still not able to load via Piwigo NG
It gives 2 msgs "Upload error" at the bottom and "Success photo uploaded to
Piwigo Server" at the top.

However upload doesn't occur

**Comment by pkrulz** [comment]
The uploads were working. My bad.
Had to update the community plugin. Also after the upload it takes a while
for the new image to be uploaded and show in the app.

**Comment by pkrulz** [comment]
I have tried this several times now. After Piwigo displays the message that
upload was successful, it takes some minutes for the image to show up in
the app and on the server. Is it due to async upload ?
In that case probably, we can msg that upload has been successfully started
and then give the upload message only when the image is completely
uploaded. My two cents
