### ISSUE TITLE
invalid url

### ISSUE THREAD

**Issue by ddhx-gh** [Piwigo/piwigo-flutter-app#95]
Hi, 
My url is right but I have this message :
![piwigo-error](https://user-images.githubusercontent.com/83832821/153761877-7bfb8119-c5bb-475c-b247-223c8f942d67.png)

I run piwigo ng on my phone and anbox on ubuntu 20.04 and it's the same issue.

An idea?
Thanks,
ddhx

**Comment by remi-martin** [comment]
Hi, can you give me you're Piwigo Address so I can figure out the issue.

**Comment by ddhx-gh** [comment]
This problem is fixed by using nd_mysqli extension instead of php mysqli.
ddhx
